ASSUME CS: CODE, DS: DATA

DATA SEGMENT
    LIST DB 02H, 01H, 04H, 03H
    COUNT EQU 0003H
DATA ENDS

CODE SEGMENT
START:  MOV AX, DATA
        MOV DS, AX
        MOV DX, COUNT
AGAIN:  MOV CX, DX
        MOV SI, OFFSET LIST
BACK:   MOV AL, [SI]
        CMP AL, [SI+1]
        JL NEXT
        XCHG AL, [SI+1]
        XCHG AL, [SI]
NEXT:   INC SI
        LOOP BACK
        DEC DX
        JNZ AGAIN
        INT 03
CODE ENDS
END START
 