ASSUME CS: CODE, DS: DATA

DATA SEGMENT
    STRING DB "ARMSTRONG$"
    REFNO EQU "$"
    COUNT EQU 0000
DATA ENDS

CODE SEGMENT
START:  MOV AX, DATA
        MOV DS, AX
        MOV CX, COUNT
        MOV SI, OFFSET STRING
        MOV AL, REFNO
BACK:   CMP AL, [SI]
        JE STOP
        INC SI
        INC CX
        JNZ BACK
STOP:   MOV AX, CX
        INT 03
CODE ENDS
END START